# Alembic migration template.

"""create feedback table

Revision ID: 36cd42e970b0
Revises: 
Create Date: 2026-09-20 01:15:41.626570

"""

# Import Alembic migration operations.
from typing import Sequence, Union

# Import Alembic operation utilities.
from alembic import op

# Import SQLAlchemy types for migration definitions.
import sqlalchemy as sa


# Define the migration revision identifier.
revision: str = '36cd42e970b0'

# Define the previous migration revision.
down_revision: Union[str, Sequence[str], None] = None

# Define optional branch labels.
branch_labels: Union[str, Sequence[str], None] = None

# Define optional migration dependencies.
depends_on: Union[str, Sequence[str], None] = None


# Apply the migration changes.
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


# Reverse the migration changes.
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
    