# Alembic migration template.

"""create notifications table

Revision ID: 84f082ff2c21
Revises: 9cf6ede1e24e
Create Date: 2026-09-20 13:28:54.893861

"""

# Import Alembic migration operations.
from typing import Sequence, Union

# Import Alembic operation utilities.
from alembic import op

# Import SQLAlchemy types for migration definitions.
import sqlalchemy as sa


# Define the migration revision identifier.
revision: str = '84f082ff2c21'

# Define the previous migration revision.
down_revision: Union[str, Sequence[str], None] = '9cf6ede1e24e'

# Define optional branch labels.
branch_labels: Union[str, Sequence[str], None] = None

# Define optional migration dependencies.
depends_on: Union[str, Sequence[str], None] = None


# Apply the migration changes.
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    # ### end Alembic commands ###


# Reverse the migration changes.
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
    