# Alembic migration template.

"""create chat history tables

Revision ID: 9cf6ede1e24e
Revises: 36cd42e970b0
Create Date: 2026-09-20 13:06:31.914784

"""

# Import Alembic migration operations.
from typing import Sequence, Union

# Import Alembic operation utilities.
from alembic import op

# Import SQLAlchemy types for migration definitions.
import sqlalchemy as sa


# Define the migration revision identifier.
revision: str = '9cf6ede1e24e'

# Define the previous migration revision.
down_revision: Union[str, Sequence[str], None] = '36cd42e970b0'

# Define optional branch labels.
branch_labels: Union[str, Sequence[str], None] = None

# Define optional migration dependencies.
depends_on: Union[str, Sequence[str], None] = None


# Apply the migration changes.
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


# Reverse the migration changes.
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('conversations')
    # ### end Alembic commands ###
    